// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	request "main/internal/api/request"
)

// AddTaskInterface is an autogenerated mock type for the AddTaskInterface type
type AddTaskInterface struct {
	mock.Mock
}

// AddTask provides a mock function with given fields: task, userID
func (_m *AddTaskInterface) AddTask(task request.AddTask, userID interface{}) error {
	ret := _m.Called(task, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(request.AddTask, interface{}) error); ok {
		r0 = rf(task, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAddTaskInterface creates a new instance of AddTaskInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAddTaskInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *AddTaskInterface {
	mock := &AddTaskInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
