// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	redis "github.com/redis/go-redis/v9"
	mock "github.com/stretchr/testify/mock"

	request "main/internal/api/request"
)

// CheckUserInterface is an autogenerated mock type for the CheckUserInterface type
type CheckUserInterface struct {
	mock.Mock
}

// CheckUser provides a mock function with given fields: creds, rds, ctx
func (_m *CheckUserInterface) CheckUser(creds request.LoginData, rds *redis.Client, ctx context.Context) (string, error) {
	ret := _m.Called(creds, rds, ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckUser")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(request.LoginData, *redis.Client, context.Context) (string, error)); ok {
		return rf(creds, rds, ctx)
	}
	if rf, ok := ret.Get(0).(func(request.LoginData, *redis.Client, context.Context) string); ok {
		r0 = rf(creds, rds, ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(request.LoginData, *redis.Client, context.Context) error); ok {
		r1 = rf(creds, rds, ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCheckUserInterface creates a new instance of CheckUserInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCheckUserInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *CheckUserInterface {
	mock := &CheckUserInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
