// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	request "main/internal/api/request"
)

// DeleteTaskInterface is an autogenerated mock type for the DeleteTaskInterface type
type DeleteTaskInterface struct {
	mock.Mock
}

// DeleteTask provides a mock function with given fields: delete, userID
func (_m *DeleteTaskInterface) DeleteTask(delete request.DeleteTaskID, userID interface{}) error {
	ret := _m.Called(delete, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(request.DeleteTaskID, interface{}) error); ok {
		r0 = rf(delete, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDeleteTaskInterface creates a new instance of DeleteTaskInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeleteTaskInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeleteTaskInterface {
	mock := &DeleteTaskInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
