// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	request "main/internal/api/request"
)

// MarkTaskDoneInterface is an autogenerated mock type for the MarkTaskDoneInterface type
type MarkTaskDoneInterface struct {
	mock.Mock
}

// MarkTaskDone provides a mock function with given fields: done, userID
func (_m *MarkTaskDoneInterface) MarkTaskDone(done request.MarkTaskDoneID, userID interface{}) error {
	ret := _m.Called(done, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkTaskDone")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(request.MarkTaskDoneID, interface{}) error); ok {
		r0 = rf(done, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMarkTaskDoneInterface creates a new instance of MarkTaskDoneInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMarkTaskDoneInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MarkTaskDoneInterface {
	mock := &MarkTaskDoneInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
