// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	request "main/internal/api/request"
)

// RegisterUserInterface is an autogenerated mock type for the RegisterUserInterface type
type RegisterUserInterface struct {
	mock.Mock
}

// RegisterUser provides a mock function with given fields: regData
func (_m *RegisterUserInterface) RegisterUser(regData request.RegistrationData) error {
	ret := _m.Called(regData)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(request.RegistrationData) error); ok {
		r0 = rf(regData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRegisterUserInterface creates a new instance of RegisterUserInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegisterUserInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *RegisterUserInterface {
	mock := &RegisterUserInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
