// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	response "main/internal/api/response"
)

// ShowTasksInterface is an autogenerated mock type for the ShowTasksInterface type
type ShowTasksInterface struct {
	mock.Mock
}

// ShowTasks provides a mock function with given fields: query, queryKey, userID
func (_m *ShowTasksInterface) ShowTasks(query string, queryKey string, userID interface{}) (response.ShowTasks, error) {
	ret := _m.Called(query, queryKey, userID)

	if len(ret) == 0 {
		panic("no return value specified for ShowTasks")
	}

	var r0 response.ShowTasks
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, interface{}) (response.ShowTasks, error)); ok {
		return rf(query, queryKey, userID)
	}
	if rf, ok := ret.Get(0).(func(string, string, interface{}) response.ShowTasks); ok {
		r0 = rf(query, queryKey, userID)
	} else {
		r0 = ret.Get(0).(response.ShowTasks)
	}

	if rf, ok := ret.Get(1).(func(string, string, interface{}) error); ok {
		r1 = rf(query, queryKey, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewShowTasksInterface creates a new instance of ShowTasksInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShowTasksInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShowTasksInterface {
	mock := &ShowTasksInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
