// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	request "main/internal/api/request"
)

// UpdateTaskInterface is an autogenerated mock type for the UpdateTaskInterface type
type UpdateTaskInterface struct {
	mock.Mock
}

// UpdateTask provides a mock function with given fields: task, userID
func (_m *UpdateTaskInterface) UpdateTask(task request.UpdateTask, userID interface{}) error {
	ret := _m.Called(task, userID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(request.UpdateTask, interface{}) error); ok {
		r0 = rf(task, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUpdateTaskInterface creates a new instance of UpdateTaskInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUpdateTaskInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *UpdateTaskInterface {
	mock := &UpdateTaskInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
